#!/usr/bin/env bash
# Die on any error.
set -e

#sh scripts/qa/phpcs_dev.sh

# Install all dependencies.
composer install

cd docroot

echo 'Preview and import drupal configs.'
../vendor/bin/drush updatedb -y
../vendor/bin/drush config-import -y
../vendor/bin/drush entity-updates -y
