<?php

/**
 * @file
 * Search module file.
 */

use Symfony\Cmf\Component\Routing\RouteObjectInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function q8_search_preprocess_config_pages__search_articles__full(array &$variables) {
  $config_pages = $variables['config_pages'];

  // Set head title.
  if ($config_pages->hasField('field_title') &&
    !$config_pages->field_title->isEmpty() &&
    ($route = \Drupal::request()->attributes->get(RouteObjectInterface::ROUTE_OBJECT))
  ) {
    $route->setDefault('_title', strip_tags($variables['content']['field_title'][0]['#text']));
  }
}
