<?php

/**
 * @file
 * Search module file.
 */

use Symfony\Cmf\Component\Routing\RouteObjectInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function q8_search_preprocess_config_pages__article_listing__full(array &$variables) {
  $config_pages = &$variables['config_pages'];

  // Set head title.
  if ($config_pages->hasField('field_title') &&
    !$config_pages->field_title->isEmpty() &&
    ($route = \Drupal::request()->attributes->get(RouteObjectInterface::ROUTE_OBJECT))
  ) {
    $route->setDefault('_title', strip_tags($variables['content']['field_title'][0]['#text']));
  }
}

/**
 * Implements hook_theme().
 */
function q8_search_theme($existing, $type, $theme, $path) {
  return [
    'search_simple_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function q8_search_views_data() {
  $data['views']['q8_search_top_summary'] = [
    'title' => t('Search top summary'),
    'area' => [
      'id' => 'search_top_summary',
    ],
  ];
  return $data;
}

/**
 * Implements q8_theme_form_views_exposed_form_alter().
 */
function q8_search_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  switch ($form_state->get('view')->id()) {
    case 'search_articles':
      $form['how_can_we_help']['#title_display'] = 'invisible';
      $form['how_can_we_help']['#attributes'] = [
        'placeholder' => t("Ask us anything. We're Experts!"),
      ];

      if ($config = config_pages_config('overview_page')) {
        if ($config->hasField('field_title') && !$config->get('field_title')->isEmpty()) {
          $form['title'] = [
            '#type' => 'processed_text',
            '#text' => $config->get('field_title')[0]->value,
            '#format' => $config->get('field_title')[0]->format,
          ];
        }
      }
      break;
  }
}
