<?php

/**
 * @file
 * Contains q8_theme.module.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function q8_theme_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the q8_theme module.
    case 'help.page.q8_theme':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Theming functions and layouts') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function q8_theme_preprocess_layout__paragraph_2_columns_image_text(array &$variables) {
  // Add alias for the current entity.
  $entity = &$variables['content']['#entity'];
  $variables['entity_id'] = $entity->id();

  // By default image is in the right column.
  $variables['img_right'] = TRUE;

  // Process paragraph attributes.
  if (
    $entity instanceof FieldableEntityInterface
    && $entity->hasField('field_style')
  ) {

    // Override image position to the left.
    $classes = [];
    foreach ($entity->get('field_style')->referencedEntities() as $class) {
      $classes[] = $class->getClasses();
    }

    if (in_array('is-left', $classes)) {
      $variables['img_right'] = FALSE;
    }

  }
}

/**
 * Implements q8_theme_form_views_exposed_form_alter().
 */
function q8_theme_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  switch ($form_state->get('view')->id()) {
    case 'featured_articles':
      $form['categories']['#title_display'] = 'invisible';
      $form['actions']['#attributes']['class'][] = 'hidden';
      break;
  }
}

/**
 * Implements q8_theme_preprocess_block__footerbanner().
 */
function q8_theme_preprocess_block__footerbanner(array &$variables) {
  // Get Request Object.
  $request = \Drupal::request();

  // If there is HTTP Exception..
  if ($exception = $request->attributes->get('exception')) {
    // Get the status code.
    $status_code = $exception->getStatusCode();

    // Hide Footer Banner for 404 pages.
    if (in_array($status_code, [403, 404])) {
      $variables['content']['#access'] = FALSE;
    }
  }
}
